### PR TITLE
[Agent] Config file, binding execution to specific cores and minor bug fix  

### LINKED ISSUE #19: [Agent] Allow binding agent execution to specific logical cores

### PR DESCRIPTION
**Pull request by kox13**
Closes #19 

This PR introduces configurable CPU core affinity via a TOML-based configuration file and fixes an OS name detection bug.

### Config file support
- Added support for .conf configuration files using TOML syntax
- Parsing is implemented using the header-only toml++ library
- Currently supported option: `core_affinity`

### CPU core binding
- Added ability to bind the agent process to specific CPU cores using `sched.h`
- Core affinity is configured via the `core_affinity` field in `agent.conf`
- Supported formats:
    - `core_affinity: [1, 2, 3]`
    - `core_affinity: [2]`
    - `core_affinity: ["5-10"]`
    - `core_affinity: ["4-10", "0-2"]`
    - `core_affinity: "all"`

### OS name detection
Fixed incorrect condition when checking the OS name.
`starts_with()` returns a boolean, so the comparison with == 0 was removed: `line.starts_with("PRETTY_NAME=")`

### CODE REVIEW

File: libs/include/toml++/toml.hpp
Comment (varev-dev) [inline libs/include/toml++/toml.hpp:1]: We are moving all dependencies except NVML to vcpkg Manifest Mode, so we shouldn't vendor toml.hpp directly in the repo (it adds unnecessary bloat to the git history).

Please delete this file and instead:
1. Add tomlplusplus to vcpkg.json.
2. Link it in CMake using find_package(tomlplusplus CONFIG REQUIRED).

File: source/agent/CMakeLists.txt [hunk 1]
```diff
@@ -40,5 +44,30 @@ else()
...
+          /usr/include
+          /usr/local/include
+)
+
+if(TOML_INCLUDE_DIR)
+    message(STATUS "Found toml++ headers: ${TOML_INCLUDE_DIR}")
+    target_include_directories(${AGENT_NAME} PRIVATE ${TOML_INCLUDE_DIR})
+else()
+    message(FATAL_ERROR "toml++ headers not found! Please clone them into libs/include/toml++")
+endif()
```
Comment (varev-dev) [inline source/agent/CMakeLists.txt]: Remove (related to moving toml++ into vcpkg)

File: CMakeLists.txt [hunk 2]
```diff
@@ -48,7 +48,7 @@ target_link_libraries(volta_proto PRIVATE
   ${CMAKE_DL_LIBS}
 )
 
-include_directories("${LOCAL_INCLUDE_DIR}/nvidia")
+include_directories("${LOCAL_INCLUDE_DIR}/nvidia" "${LOCAL_INCLUDE_DIR}/toml++")
```
Comment (varev-dev) [inline CMakeLists.txt]: Remove (related to moving toml++ into vcpkg)

**Review by varev-dev — CHANGES_REQUESTED** [review]

File: libs/include/toml++/toml.hpp
Comment (kox13) [reply libs/include/toml++/toml.hpp:1]: Done

File: source/agent/CMakeLists.txt (hunk 1 above)
Comment (kox13) [reply source/agent/CMakeLists.txt]: Done

File: CMakeLists.txt (hunk 2 above)
Comment (kox13) [reply CMakeLists.txt]: Done

**Review by varev-dev — APPROVED** [review]
lgtm
